# Generated by Django 3.1.3 on 2020-11-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201116_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('normal', 'normal'), ('low', 'low')], default='high', max_length=50),
        ),
    ]
